/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HHS_PROJGR6;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());

        System.out.println("Miek is homo");
    }
}
