/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HHS_PROJGR6;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    // TODO: make tests for startup
}
