/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HHS_PROJGR6;

import org.junit.Test;
import static org.junit.Assert.*;

public class DijkstraTest {
    @Test
    public static void testGraph() {
        // maak entities
        // maak graph van 4x4
    }

    @Test
    public static void testRouteUp() {
        // maak entities
        // maak graph van 4x4
    }

    @Test
    public static void testRouteDown() {
        // maak entities
        // maak graph van 4x4
    }
}
