/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HHS_PROJGR6;

import org.junit.Test;
import static org.junit.Assert.*;

public class EntityTest {
    @Test
    public static void movementPerFrame() {
        // maak entities
        // test alle entities op frames
    }

    @Test
    public static void checkoutAfterSaidTime() {
        // maak guest
        // Test guest op status
    }

    @Test
    public static void somethingToTest() {
        // maak entities
        // maak graph van 4x4
    }
}
