/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HHS_PROJGR6;

public class App {
    public String getGreeting() {
        return "Hello world from group 6.";
    }

    // Ghallo

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
