/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HHS_PROJGR6;

public class App {
    public String getGreeting() {
        return "Hello world. Kijken of dit werkt2.0"; 
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}




